"""Structured basis-dependent Ridge scan for the fixed Frozen MP model.

The ten Frozen MP columns are first normalized with a train-only RMS scale.
Rather than fitting ten free regularization values, the diagonal penalty is
generated by three shared hyperparameters:

    lambda_(p,m) = lambda0 * alpha**g(p) * beta**m

Only A/C contiguous blocked-CV is used to select the three hyperparameters.
B targets are materialized only after the selected triple is frozen.  The
task writes exactly three result files and keeps all other diagnostics in
memory.
"""

# ruff: noqa: E402,E501,I001

from __future__ import annotations

import math
import os
import sys
from concurrent.futures import ProcessPoolExecutor, as_completed
from datetime import UTC, datetime
from multiprocessing import freeze_support
from pathlib import Path
from typing import Any

for _thread_name in (
    "OMP_NUM_THREADS",
    "OPENBLAS_NUM_THREADS",
    "MKL_NUM_THREADS",
    "NUMEXPR_NUM_THREADS",
    "VECLIB_MAXIMUM_THREADS",
):
    os.environ[_thread_name] = "1"

import numpy as np
import pandas as pd

SCRIPTS_ROOT = Path(__file__).resolve().parent.parent
PROJECT_ROOT = SCRIPTS_ROOT.parent
if str(SCRIPTS_ROOT) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_ROOT))

from behavior_model import frozen_neighborhood_memory_ridge_scan as frozen_model
from behavior_model.evaluation import calculate_nmse
from behavior_model.run_scenario2_failed14_frozen_mp_normalized_uniform_ridge_5b import (
    _fit_normalized_ridge as _uniform_fit_normalized_ridge,
)
from behavior_model.run_scenario2_failed14_frozen_mp_normalized_uniform_ridge_5b import (
    _fit_raw_ridge as _uniform_fit_raw_ridge,
)
from behavior_model.run_scenario2_failed14_frozen_mp_normalized_uniform_ridge_5b import (
    _build_basis as _uniform_build_basis,
)
from behavior_model.run_scenario2_failed14_frozen_mp_normalized_uniform_ridge_5b import (
    _frozen_reproduction_gate as _uniform_frozen_reproduction_gate,
)
from behavior_model.run_scenario2_failed14_frozen_mp_normalized_uniform_ridge_5b import (
    _load_reference as _uniform_load_reference,
)
from behavior_model.run_scenario2_failed14_frozen_mp_normalized_uniform_ridge_5b import (
    _protection_check as _uniform_protection_check,
)
from behavior_model.run_scenario2_failed14_frozen_mp_normalized_uniform_ridge_5b import (
    _snapshot as _uniform_snapshot,
)


TASK_NAME = "scenario_2_failed14_frozen_mp_normalized_basis_dependent_ridge_5B"
RESULT_ROOT = PROJECT_ROOT / "results" / "behavior_model" / TASK_NAME
WORK_LOG = PROJECT_ROOT / "work_logs" / "behavior_model" / "execution_log.txt"
HANDOFF_LOG = PROJECT_ROOT / "work_logs" / "codex_handoff" / "codex_handoff.txt"

FAILED_STATE_IDS = (
    187,
    189,
    195,
    196,
    199,
    206,
    323,
    327,
    330,
    335,
    340,
    344,
    346,
    354,
)
ORDERS = (1, 2, 3, 5, 7, 9)
MEMORY = {1: 3, 2: 2, 3: 2, 5: 1, 7: 1, 9: 1}
BASIS_IDS = ((1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (3, 0), (3, 1), (5, 0), (7, 0), (9, 0))
ORDER_LEVEL = {1: 0, 2: 1, 3: 2, 5: 3, 7: 4, 9: 5}
K = 10
DMAX = 2
CV_FOLDS = 3
CPU_TARGET = 0.90
FROZEN_LAMBDA = 1e-8
UNIFORM_LAMBDA = 10.0 ** -6.25
TIE_TOLERANCE_DB = 1e-9
LOG10_LAMBDA0_COARSE = np.arange(-10.0, -4.0 + 1e-12, 0.5, dtype=np.float64)
ALPHA_COARSE = np.asarray([1.0, np.sqrt(2.0), 2.0, 4.0, 8.0, 16.0], dtype=np.float64)
BETA_COARSE = np.asarray([1.0, np.sqrt(2.0), 2.0, 4.0], dtype=np.float64)
FROZEN_REFERENCE_ROOT = PROJECT_ROOT / "results" / "behavior_model" / "scenario_2_failed14_frozen_neighborhood_memory_ridge_scan_5B"
FROZEN_REFERENCE_FILE = FROZEN_REFERENCE_ROOT / "tables" / "frozen_baseline_regression.csv"
UNIFORM_RESULT_FILE = PROJECT_ROOT / "results" / "behavior_model" / "scenario_2_failed14_frozen_mp_normalized_uniform_ridge_5B" / "final_per_state_metrics.csv"
PROTECTED_RESULT_DIRS = {
    "formal_retrieval": PROJECT_ROOT / "results" / "behavior_fingerprint_lut_retrieval" / "scenario_2_C2_to_Aend",
    "all_ilc_frozen": PROJECT_ROOT / "results" / "behavior_fingerprint_ranking_consistency" / "scenario_2_all_ilc",
    "unified_capacity": PROJECT_ROOT / "results" / "behavior_model" / "scenario_2_unified_odd_order_mp_capacity_scan_5B",
    "odd_order_scan": PROJECT_ROOT / "results" / "behavior_model" / "scenario_2_failed14_odd_order_mp_order_dependent_memory_scan_5B",
    "p5_ridge": PROJECT_ROOT / "results" / "behavior_model" / "scenario_2_failed14_P5_variable_memory_ridge_scan_5B",
    "p5_order2": PROJECT_ROOT / "results" / "behavior_model" / "scenario_2_failed14_P5_with_order2_variable_memory_OLS_scan_5B",
    "frozen_neighborhood": FROZEN_REFERENCE_ROOT,
    "sparse_gmp": PROJECT_ROOT / "results" / "behavior_model" / "scenario_2_failed14_frozen_mp_residual_sparse_gmp_5B",
    "multibranch": PROJECT_ROOT / "results" / "behavior_model" / "scenario_2_failed14_multibranch_independent_basis_OLS_scan_5B",
    "normalized_uniform": PROJECT_ROOT / "results" / "behavior_model" / "scenario_2_failed14_frozen_mp_normalized_uniform_ridge_5B",
}

_WORKER_DISCOVERY: dict[int, dict[str, tuple[np.ndarray, np.ndarray]]] = {}


def _write_frame(frame: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(path, index=False, encoding="utf-8-sig", float_format="%.17g", na_rep="NaN")


def _lambda_vector(lambda0: float, alpha: float, beta_memory: float) -> np.ndarray:
    lambda0 = float(lambda0)
    alpha = float(alpha)
    beta_memory = float(beta_memory)
    if not np.isfinite(lambda0) or lambda0 <= 0 or not np.isfinite(alpha) or alpha < 1 or not np.isfinite(beta_memory) or beta_memory < 1:
        raise ValueError("lambda0 must be positive and alpha/beta must be >= 1")
    values = np.asarray([lambda0 * alpha ** ORDER_LEVEL[order] * beta_memory ** memory for order, memory in BASIS_IDS], dtype=np.float64)
    if not np.all(np.isfinite(values)) or np.any(values <= 0):
        raise ValueError("basis-dependent lambda vector is not finite/positive")
    return values


def _lambda_vector_gate() -> dict[str, Any]:
    actual = _lambda_vector(1e-7, 2.0, 2.0)
    expected = np.asarray([1e-7, 2e-7, 4e-7, 2e-7, 4e-7, 4e-7, 8e-7, 8e-7, 1.6e-6, 3.2e-6], dtype=np.float64)
    return {"pass": bool(np.allclose(actual, expected, rtol=1e-12, atol=0.0)), "actual": actual, "expected": expected}


def _fit_weighted_normalized(phi_train: np.ndarray, y_train: np.ndarray, lambda0: float, alpha: float, beta_memory: float) -> dict[str, Any]:
    phi_train = np.asarray(phi_train, dtype=np.complex128)
    y_train = np.asarray(y_train, dtype=np.complex128).reshape(-1)
    scale = np.sqrt(np.mean(np.abs(phi_train) ** 2, axis=0))
    if not np.all(np.isfinite(scale)) or np.any(scale <= 0):
        raise RuntimeError("Invalid RMS scale.")
    phi_norm = phi_train / scale[None, :]
    n_samples = phi_norm.shape[0]
    lambda_vector = _lambda_vector(lambda0, alpha, beta_memory)
    penalty = np.diag(np.sqrt(n_samples * lambda_vector)).astype(np.complex128)
    phi_aug = np.vstack((phi_norm, penalty))
    y_aug = np.concatenate((y_train, np.zeros(K, dtype=np.complex128)))
    beta_hat, _, rank, singular_aug = np.linalg.lstsq(phi_aug, y_aug, rcond=None)
    singular_norm = np.asarray(np.linalg.svd(phi_norm, compute_uv=False), dtype=np.float64)
    return {
        "beta": np.asarray(beta_hat, dtype=np.complex128),
        "scale": scale,
        "rank": int(rank),
        "singular": singular_norm,
        "singular_augmented": np.asarray(singular_aug, dtype=np.float64),
        "lambda_vector": lambda_vector,
        "ridge_penalty": float(np.sum(lambda_vector * np.abs(beta_hat) ** 2)),
    }


def _prepare_discovery_payload() -> tuple[dict[int, dict[str, tuple[np.ndarray, np.ndarray]]], list[dict[str, Any]]]:
    payload: dict[int, dict[str, tuple[np.ndarray, np.ndarray]]] = {}
    records: list[dict[str, Any]] = []
    for state_id in FAILED_STATE_IDS:
        prepared = frozen_model.prepare_state(state_id)
        a_phi, a_y = _uniform_build_basis(prepared.aend_A_input, prepared.aend_A_output)
        c_phi, c_y = _uniform_build_basis(prepared.c2_C_input, prepared.c2_C_output)
        payload[state_id] = {"Aend": (a_phi, a_y), "C2": (c_phi, c_y)}
        records.append({"state_id": int(state_id), "ilc_A_end": int(prepared.ilc_A_end), "A_valid_length": int(a_phi.shape[0]), "C_valid_length": int(c_phi.shape[0]), "B_target_retained": False})
        del prepared
    return payload, records


def _worker_init(payload: dict[int, dict[str, tuple[np.ndarray, np.ndarray]]]) -> None:
    global _WORKER_DISCOVERY
    _WORKER_DISCOVERY = payload


def _blocked_indices(length: int) -> list[np.ndarray]:
    return [np.asarray(block, dtype=np.int64) for block in np.array_split(np.arange(length, dtype=np.int64), CV_FOLDS)]


def _cv_task(task: tuple[int, float, float, float, int, str]) -> dict[str, Any]:
    config_id, lambda0, alpha, beta_memory, state_id, side = task
    phi, y = _WORKER_DISCOVERY[state_id][side]
    blocks = _blocked_indices(phi.shape[0])
    fold_values: list[float] = []
    rank_values: list[int] = []
    for validation_block in range(CV_FOLDS):
        validation_index = blocks[validation_block]
        train_index = np.concatenate([blocks[index] for index in range(CV_FOLDS) if index != validation_block])
        fit = _fit_weighted_normalized(phi[train_index], y[train_index], lambda0, alpha, beta_memory)
        prediction = (phi[validation_index] / fit["scale"][None, :]) @ fit["beta"]
        fold_values.append(float(calculate_nmse(y[validation_index], prediction)))
        rank_values.append(int(fit["rank"]))
    return {"config_id": int(config_id), "lambda0": float(lambda0), "alpha": float(alpha), "beta_memory": float(beta_memory), "state_id": int(state_id), "side": side, "CV_NMSE_dB": float(np.mean(fold_values)), "rank_min": int(min(rank_values))}


def _configuration_rows(stage: str, configs: list[tuple[float, float, float]], start_id: int) -> pd.DataFrame:
    rows = []
    for offset, (lambda0, alpha, beta_memory) in enumerate(configs):
        rows.append({"config_id": start_id + offset, "stage": stage, "lambda0": float(lambda0), "alpha": float(alpha), "beta_memory": float(beta_memory), "log10_lambda0": float(np.log10(lambda0)), "log2_alpha": float(np.log2(alpha)), "log2_beta": float(np.log2(beta_memory))})
    return pd.DataFrame(rows)


def _scan_configurations(config_frame: pd.DataFrame, payload: dict[int, dict[str, tuple[np.ndarray, np.ndarray]]], workers: int) -> pd.DataFrame:
    tasks = [(int(row.config_id), float(row.lambda0), float(row.alpha), float(row.beta_memory), state_id, side) for row in config_frame.itertuples(index=False) for state_id in FAILED_STATE_IDS for side in ("Aend", "C2")]
    rows: list[dict[str, Any]] = []
    errors: list[str] = []
    print(f"weighted Ridge {config_frame.stage.iloc[0]} tasks: {len(tasks)}; workers={workers}", flush=True)
    with ProcessPoolExecutor(max_workers=workers, initializer=_worker_init, initargs=(payload,)) as executor:
        futures = [executor.submit(_cv_task, task) for task in tasks]
        for done, future in enumerate(as_completed(futures), start=1):
            try:
                rows.append(future.result())
            except Exception as exc:  # pragma: no cover
                errors.append(f"{type(exc).__name__}: {exc}")
            if done % 500 == 0 or done == len(futures):
                print(f"weighted Ridge {config_frame.stage.iloc[0]} tasks: {done}/{len(futures)}", flush=True)
    if errors:
        raise RuntimeError("weighted Ridge worker failure: " + " | ".join(errors[:5]))
    detail = pd.DataFrame(rows)
    summaries: list[dict[str, Any]] = []
    for config in config_frame.itertuples(index=False):
        current = detail.loc[detail["config_id"] == int(config.config_id)]
        a = current.loc[current.side == "Aend", "CV_NMSE_dB"].to_numpy(dtype=float)
        c = current.loc[current.side == "C2", "CV_NMSE_dB"].to_numpy(dtype=float)
        if a.size != 14 or c.size != 14:
            raise RuntimeError(f"config {config.config_id} has incomplete state-side CV results")
        a_median, c_median = float(np.median(a)), float(np.median(c))
        a_q75, c_q75 = float(np.quantile(a, 0.75)), float(np.quantile(c, 0.75))
        a_worst, c_worst = float(np.max(a)), float(np.max(c))
        summaries.append({"config_id": int(config.config_id), "stage": str(config.stage), "lambda0": float(config.lambda0), "alpha": float(config.alpha), "beta_memory": float(config.beta_memory), "log10_lambda0": float(config.log10_lambda0), "log2_alpha": float(config.log2_alpha), "log2_beta": float(config.log2_beta), "A_CV_median_dB": a_median, "A_CV_q75_dB": a_q75, "A_CV_worst_dB": a_worst, "C_CV_median_dB": c_median, "C_CV_q75_dB": c_q75, "C_CV_worst_dB": c_worst, "BalancedMedian_dB": max(a_median, c_median), "BalancedQ75_dB": max(a_q75, c_q75), "BalancedWorst_dB": max(a_worst, c_worst), "rank_min": int(current.rank_min.min())})
    return pd.DataFrame(summaries).sort_values("config_id").reset_index(drop=True)


def _select_configuration(frame: pd.DataFrame) -> tuple[pd.Series, dict[str, Any]]:
    best = float(frame["BalancedMedian_dB"].min())
    ties = frame.loc[np.abs(frame["BalancedMedian_dB"] - best) < TIE_TOLERANCE_DB].copy()
    ties = ties.sort_values(["BalancedQ75_dB", "BalancedWorst_dB", "alpha", "beta_memory", "lambda0"], ascending=[True, True, True, True, True], kind="mergesort")
    selected = ties.iloc[0]
    return selected, {"best_balanced_median_dB": best, "tie_count_within_1e-9_dB": int(ties.shape[0]), "selected_config_id": int(selected.config_id), "selected_lambda0": float(selected.lambda0), "selected_alpha": float(selected.alpha), "selected_beta_memory": float(selected.beta_memory)}


def _local_refinement_configs(coarse_best: pd.Series) -> list[tuple[float, float, float]]:
    log_lambda = float(coarse_best.log10_lambda0)
    log_alpha = float(coarse_best.log2_alpha)
    log_beta = float(coarse_best.log2_beta)
    configs: dict[tuple[float, float, float], tuple[float, float, float]] = {}
    for ll in np.arange(log_lambda - 0.5, log_lambda + 0.5 + 1e-12, 0.125):
        for la in np.arange(log_alpha - 0.75, log_alpha + 0.75 + 1e-12, 0.25):
            for lb in np.arange(log_beta - 0.75, log_beta + 0.75 + 1e-12, 0.25):
                ll_clipped = float(np.clip(ll, -12.0, -2.0))
                la_clipped = float(np.clip(la, 0.0, 5.0))
                lb_clipped = float(np.clip(lb, 0.0, 3.0))
                key = (round(ll_clipped, 12), round(la_clipped, 12), round(lb_clipped, 12))
                configs[key] = (10.0 ** ll_clipped, 2.0 ** la_clipped, 2.0 ** lb_clipped)
    return [configs[key] for key in sorted(configs)]


def _uniform_equivalence_gate(final_rows: pd.DataFrame) -> dict[str, Any]:
    if not UNIFORM_RESULT_FILE.is_file():
        raise FileNotFoundError(f"previous normalized uniform result missing: {UNIFORM_RESULT_FILE}")
    previous = pd.read_csv(UNIFORM_RESULT_FILE).set_index("state_id").loc[list(FAILED_STATE_IDS)]
    current = final_rows.set_index("state_id").loc[list(FAILED_STATE_IDS)]
    checks: list[dict[str, Any]] = []
    for state_id in FAILED_STATE_IDS:
        differences = {}
        for metric in ("A_train", "A_B", "C_train", "C_B"):
            current_value = float(current.loc[state_id, f"UniformNorm_{metric}"])
            old_value = float(previous.loc[state_id, f"Selected_{'A_train' if metric == 'A_train' else 'A_B' if metric == 'A_B' else 'C_train' if metric == 'C_train' else 'C_B'}"])
            differences[metric] = current_value - old_value
        checks.append({"state_id": int(state_id), "max_abs_difference_dB": float(max(abs(value) for value in differences.values())), "differences_dB": differences})
    maximum = max(item["max_abs_difference_dB"] for item in checks)
    return {"pass": bool(maximum < 1e-6), "maximum_abs_difference_dB": maximum, "checks": checks}


def _fit_final_rows(selected_lambda0: float, selected_alpha: float, selected_beta: float) -> tuple[pd.DataFrame, list[dict[str, float]]]:
    rows: list[dict[str, Any]] = []
    conditions: list[dict[str, float]] = []
    for state_id in FAILED_STATE_IDS:
        prepared = frozen_model.prepare_state(state_id)
        a_phi, a_y = _uniform_build_basis(prepared.aend_A_input, prepared.aend_A_output)
        c_phi, c_y = _uniform_build_basis(prepared.c2_C_input, prepared.c2_C_output)
        a_b_phi, a_b_y = _uniform_build_basis(prepared.aend_B_input, prepared.aend_B_output)
        c_b_phi, c_b_y = _uniform_build_basis(prepared.c2_B_input, prepared.c2_B_output)
        row: dict[str, Any] = {"state_id": int(state_id)}
        condition_row: dict[str, float] = {"state_id": float(state_id)}
        for label, train_phi, train_y, b_phi, b_y in (("A", a_phi, a_y, a_b_phi, a_b_y), ("C", c_phi, c_y, c_b_phi, c_b_y)):
            frozen_fit = _uniform_fit_raw_ridge(train_phi, train_y, FROZEN_LAMBDA)
            uniform_fit = _uniform_fit_normalized_ridge(train_phi, train_y, UNIFORM_LAMBDA)
            weighted_fit = _fit_weighted_normalized(train_phi, train_y, selected_lambda0, selected_alpha, selected_beta)
            raw_prediction = train_phi @ frozen_fit["theta"]
            raw_b_prediction = b_phi @ frozen_fit["theta"]
            uniform_prediction = (train_phi / uniform_fit["scale"][None, :]) @ uniform_fit["beta"]
            uniform_b_prediction = (b_phi / uniform_fit["scale"][None, :]) @ uniform_fit["beta"]
            weighted_prediction = (train_phi / weighted_fit["scale"][None, :]) @ weighted_fit["beta"]
            weighted_b_prediction = (b_phi / weighted_fit["scale"][None, :]) @ weighted_fit["beta"]
            for prefix, train_prediction, b_prediction in (("Frozen", raw_prediction, raw_b_prediction), ("UniformNorm", uniform_prediction, uniform_b_prediction), ("Weighted", weighted_prediction, weighted_b_prediction)):
                row[f"{prefix}_{label}_train"] = float(calculate_nmse(train_y, train_prediction))
                row[f"{prefix}_{label}_B"] = float(calculate_nmse(b_y, b_prediction))
                row[f"{prefix}_{label}_gap"] = row[f"{prefix}_{label}_B"] - row[f"{prefix}_{label}_train"]
            condition_row[f"{label}_raw_condition"] = float(np.linalg.cond(train_phi))
            condition_row[f"{label}_normalized_condition"] = float(np.linalg.cond(train_phi / uniform_fit["scale"][None, :]))
        for prefix in ("Frozen", "UniformNorm", "Weighted"):
            row[f"{prefix}_worst4"] = max(row[f"{prefix}_A_train"], row[f"{prefix}_A_B"], row[f"{prefix}_C_train"], row[f"{prefix}_C_B"])
        for suffix in ("A_train", "A_B", "C_train", "C_B", "worst4"):
            row[f"Weighted_minus_Frozen_{suffix}"] = row[f"Weighted_{suffix}"] - row[f"Frozen_{suffix}"]
        rows.append(row)
        conditions.append(condition_row)
        del prepared
    return pd.DataFrame(rows).sort_values("state_id").reset_index(drop=True), conditions


def _summary_text(summary: pd.DataFrame, selection: dict[str, Any], final_rows: pd.DataFrame, conditions: list[dict[str, float]], uniform_gate: dict[str, Any], lambda_gate: dict[str, Any], frozen_gate: dict[str, Any], protection: dict[str, Any], workers: int, coarse_count: int, refine_count: int) -> str:
    medians = {model: {metric: float(final_rows[f"{model}_{metric}"].median()) for metric in ("A_train", "A_B", "C_train", "C_B", "worst4")} for model in ("Frozen", "UniformNorm", "Weighted")}
    deltas = {metric: float(final_rows[f"Weighted_minus_Frozen_{metric}"].median()) for metric in ("A_train", "A_B", "C_train", "C_B", "worst4")}
    raw_condition = [value for row in conditions for value in (row["A_raw_condition"], row["C_raw_condition"])]
    normalized_condition = [value for row in conditions for value in (row["A_normalized_condition"], row["C_normalized_condition"])]
    lines = [
        TASK_NAME,
        "Train-only RMS-normalized Frozen MP with structured basis-dependent Ridge.",
        "",
        "Experiment",
        f"- States: {list(FAILED_STATE_IDS)} (exactly 14 Frozen failure states).",
        f"- Frozen MP orders={list(ORDERS)}, memory=[3,2,2,1,1,1], K={K}, dmax={DMAX}.",
        "- Canonical pipeline: actual input -> full-record Rough/Fine -> fixed ABC ownership -> segment-wise complex-gain adjustment.",
        "- ABC: A=[0:12288), B=[12288:17203), C=[17203:24576); valid lengths=12286/4913/7371.",
        "",
        "Structured penalty",
        "- Basis normalization: train-only RMS scaling, no centering and no target normalization.",
        "- lambda_(p,m) = lambda0 * alpha^g(p) * beta^m, with g(1,2,3,5,7,9)=(0,1,2,3,4,5).",
        f"- Coarse grid: lambda0 log10={list(LOG10_LAMBDA0_COARSE)}, alpha={list(ALPHA_COARSE)}, beta={list(BETA_COARSE)}; configurations={coarse_count}.",
        f"- Local refinement: log10(lambda0) step=0.125 over ±0.5, log2(alpha)/log2(beta) step=0.25 over ±0.75 with bounds lambda0∈[1e-12,1e-2], alpha∈[1,32], beta∈[1,8]; unique configurations={refine_count}.",
        f"- Final selected lambda0={selection['selected_lambda0']:.17g}, alpha={selection['selected_alpha']:.17g}, beta_memory={selection['selected_beta_memory']:.17g}; best BalancedMedian={selection['best_balanced_median_dB']:.9f} dB.",
        "- The same three hyperparameters are shared by all 14 states and by Aend/C2.",
        "",
        "Final ten basis penalties",
    ]
    final_lambda = _lambda_vector(selection["selected_lambda0"], selection["selected_alpha"], selection["selected_beta_memory"])
    for basis, value in zip(BASIS_IDS, final_lambda, strict=True):
        lines.append(f"- lambda_{basis[0]},{basis[1]} = {value:.17g}")
    lines.extend(["", "CV and final metrics (dB)", "model | A train | A→B | C train | C→B | worst-four"])
    for model in ("Frozen", "UniformNorm", "Weighted"):
        item = medians[model]
        lines.append(f"{model} | {item['A_train']:.6f} | {item['A_B']:.6f} | {item['C_train']:.6f} | {item['C_B']:.6f} | {item['worst4']:.6f}")
    lines.extend([
        "",
        "Weighted minus Frozen (negative means improvement)",
        *[f"- {metric}: {value:+.6f} dB" for metric, value in deltas.items()],
        f"- worst-four improved states={int((final_rows['Weighted_minus_Frozen_worst4'] < 0).sum())}/{len(final_rows)}; degraded states={int((final_rows['Weighted_minus_Frozen_worst4'] > 0).sum())}/{len(final_rows)}.",
        f"- Aend gap median: Frozen={float(final_rows['Frozen_A_gap'].median()):.6f}, Weighted={float(final_rows['Weighted_A_gap'].median()):.6f}, delta={float((final_rows['Weighted_A_gap']-final_rows['Frozen_A_gap']).median()):+.6f} dB.",
        f"- C2 gap median: Frozen={float(final_rows['Frozen_C_gap'].median()):.6f}, Weighted={float(final_rows['Weighted_C_gap'].median()):.6f}, delta={float((final_rows['Weighted_C_gap']-final_rows['Frozen_C_gap']).median()):+.6f} dB.",
        "",
        "Numerical diagnostics",
        f"- raw basis condition number median={float(np.median(raw_condition)):.6g}, max={float(np.max(raw_condition)):.6g}.",
        f"- normalized basis condition number median={float(np.median(normalized_condition)):.6g}, max={float(np.max(normalized_condition)):.6g}.",
        "- Condition number is auxiliary evidence only; cross-segment B performance determines the conclusion.",
        "",
        "Gates",
        f"- Frozen reproduction gate={frozen_gate['pass']}; maximum absolute error={frozen_gate['maximum_abs_error_dB']:.3g} dB.",
        f"- lambda-vector gate={lambda_gate['pass']}; uniform-equivalence gate={uniform_gate['pass']} (max abs difference={uniform_gate['maximum_abs_difference_dB']:.3g} dB).",
        "- B target used for lambda0/alpha/beta selection=False; B was opened only after the selected triple was frozen=True.",
        f"- raw data unchanged={protection['data_raw_unchanged']}; protected historical results unchanged={protection['protected_result_dirs_unchanged']}.",
        "",
        "Conclusion",
        "- Structured basis-dependent Ridge is a three-hyperparameter regularization experiment, not a new MP structure.",
        "- A lower training NMSE or lower normalized condition number does not establish success; Aend→B and especially C2→B must improve.",
        "- This task does not generate figures, Excel, JSON/candidate files, per-fold outputs, cache, coefficients, 425-state validation, GMP, LUT retrieval, Real-B shareability or low-bandwidth results.",
        "- Frozen MP remains the reference model and was not automatically replaced.",
        "",
        "Result files",
        f"- {RESULT_ROOT / 'ridge_search_summary.csv'}",
        f"- {RESULT_ROOT / 'final_per_state_metrics.csv'}",
        f"- {RESULT_ROOT / 'final_result_summary.txt'}",
    ])
    return "\n".join(lines) + "\n"


def main() -> None:
    freeze_support()
    print(f"Starting {TASK_NAME}", flush=True)
    if len(FAILED_STATE_IDS) != 14 or K != 10 or DMAX != 2 or len(LOG10_LAMBDA0_COARSE) != 13 or len(ALPHA_COARSE) != 6 or len(BETA_COARSE) != 4:
        raise RuntimeError("fixed experiment definition gate failed")
    before = _uniform_snapshot()
    reference = _uniform_load_reference()
    logical_cpu_count = int(os.cpu_count() or 1)
    workers = max(1, int(math.floor(CPU_TARGET * logical_cpu_count)))
    print(f"logical_cpu_count={logical_cpu_count}; worker_count={workers}; target={CPU_TARGET:.2f}", flush=True)
    frozen_gate = _uniform_frozen_reproduction_gate(reference)
    if not frozen_gate["pass"]:
        raise RuntimeError(f"Frozen reproduction gate failed: {frozen_gate['maximum_abs_error_dB']}")
    lambda_gate = _lambda_vector_gate()
    if not lambda_gate["pass"]:
        raise RuntimeError("basis-dependent lambda-vector gate failed")
    print(f"Frozen reproduction gate PASS; max_abs_error_dB={frozen_gate['maximum_abs_error_dB']:.3g}", flush=True)
    print("basis-dependent lambda-vector gate PASS", flush=True)

    discovery_payload, discovery_records = _prepare_discovery_payload()
    coarse_configs = [(10.0 ** float(log_lambda), float(alpha), float(beta_memory)) for log_lambda in LOG10_LAMBDA0_COARSE for alpha in ALPHA_COARSE for beta_memory in BETA_COARSE]
    coarse_frame = _configuration_rows("coarse", coarse_configs, 0)
    coarse_summary = _scan_configurations(coarse_frame, discovery_payload, workers)
    coarse_best, coarse_selection = _select_configuration(coarse_summary)
    print(f"coarse best: lambda0={coarse_best.lambda0:.17g}, alpha={coarse_best.alpha:.17g}, beta={coarse_best.beta_memory:.17g}, BalancedMedian={coarse_best.BalancedMedian_dB:.6f} dB", flush=True)
    refine_configs_all = _local_refinement_configs(coarse_best)
    coarse_keys = {
        (round(float(np.log10(lambda0)), 12), round(float(np.log2(alpha)), 12), round(float(np.log2(beta_memory)), 12))
        for lambda0, alpha, beta_memory in coarse_configs
    }
    refine_configs = [
        config
        for config in refine_configs_all
        if (round(float(np.log10(config[0])), 12), round(float(np.log2(config[1])), 12), round(float(np.log2(config[2])), 12)) not in coarse_keys
    ]
    refine_frame = _configuration_rows("refinement", refine_configs, len(coarse_configs))
    refine_summary = _scan_configurations(refine_frame, discovery_payload, workers)
    combined_summary = pd.concat([coarse_summary, refine_summary], ignore_index=True)
    selected_row, selection = _select_configuration(combined_summary)
    selection["coarse_best"] = {key: float(coarse_best[key]) if key in {"lambda0", "alpha", "beta_memory", "BalancedMedian_dB"} else coarse_best[key] for key in ("lambda0", "alpha", "beta_memory", "BalancedMedian_dB")}
    print(f"selected weighted Ridge: lambda0={selection['selected_lambda0']:.17g}, alpha={selection['selected_alpha']:.17g}, beta={selection['selected_beta_memory']:.17g}, BalancedMedian={selection['best_balanced_median_dB']:.6f} dB", flush=True)
    del discovery_payload

    final_rows, conditions = _fit_final_rows(selection["selected_lambda0"], selection["selected_alpha"], selection["selected_beta_memory"])
    uniform_gate = _uniform_equivalence_gate(final_rows)
    if not uniform_gate["pass"]:
        raise RuntimeError(f"uniform-equivalence gate failed: {uniform_gate['maximum_abs_difference_dB']}")
    RESULT_ROOT.mkdir(parents=True, exist_ok=True)
    combined_summary["is_selected"] = combined_summary["config_id"].eq(int(selection["selected_config_id"]))
    _write_frame(combined_summary.drop(columns=["rank_min"]), RESULT_ROOT / "ridge_search_summary.csv")
    _write_frame(final_rows.drop(columns=[column for column in final_rows.columns if column.endswith("_gap")]), RESULT_ROOT / "final_per_state_metrics.csv")
    after = _uniform_snapshot()
    protection = _uniform_protection_check(before, after)
    if not protection["all_protected_unchanged"]:
        raise RuntimeError("raw data or protected historical result changed")
    summary = _summary_text(combined_summary, selection, final_rows, conditions, uniform_gate, lambda_gate, frozen_gate, protection, workers, len(coarse_configs), len(refine_configs))
    (RESULT_ROOT / "final_result_summary.txt").write_text(summary, encoding="utf-8")
    timestamp = datetime.now(UTC).isoformat()
    log = (
        f"{TASK_NAME} completed: states=14, coarse_configs={len(coarse_configs)}, refinement_configs={len(refine_configs)}, "
        f"total_configs={len(combined_summary)}, selected_lambda0={selection['selected_lambda0']:.17g}, alpha={selection['selected_alpha']:.17g}, beta={selection['selected_beta_memory']:.17g}, "
        f"CV_fits={(len(coarse_configs) + len(refine_configs)) * 14 * 2 * 3}, workers={workers}, frozen_gate={frozen_gate['pass']}, lambda_vector_gate={lambda_gate['pass']}, uniform_gate={uniform_gate['pass']}, raw/protected unchanged={protection['all_protected_unchanged']}. "
        f"Only three result files were written under {RESULT_ROOT}; no figures, Excel, cache, coefficients, or retrieval were generated."
    )
    WORK_LOG.parent.mkdir(parents=True, exist_ok=True)
    HANDOFF_LOG.parent.mkdir(parents=True, exist_ok=True)
    with WORK_LOG.open("a", encoding="utf-8") as handle:
        handle.write(f"\n\n[{timestamp}] {TASK_NAME}\n{log}\n")
    with HANDOFF_LOG.open("a", encoding="utf-8") as handle:
        handle.write(f"\n\n{timestamp} | behavior_model 新派生任务：Frozen MP normalized basis-dependent Ridge\n{log}\n")
    print(log, flush=True)


if __name__ == "__main__":
    main()
