"""Fixed facts for the complex-baseband observation-rate grid."""

from __future__ import annotations

BASE_SIGNAL_BANDWIDTH_HZ = 20_000_000
FS_INPUT_HZ = 100_000_000
SAMPLE_RATE_STEP_HZ = 2_000_000
SAMPLE_RATE_INDEX_MIN = 1
SAMPLE_RATE_INDEX_MAX = 50
NORMALIZED_RATIO_DENOMINATOR = 10
RESAMPLER_NAME = "scipy.signal.resample_poly"
RESAMPLER_WINDOW = ("kaiser", 5.0)
RESAMPLER_PADTYPE = "constant"
RESAMPLER_CVAL = 0.0
EDGE_POLICY = "keep"
MANUAL_GROUP_DELAY_COMPENSATION_APPLIED = False
EXPLICIT_SAMPLE_SHIFT_APPLIED = 0
INPUT_TIME_ORIGIN_S = 0.0
OUTPUT_TIME_ORIGIN_S = 0.0
OUTPUT_TIME_ORIGIN_ALIGNED = True
ADDITIONAL_DELAY_COMPENSATION_REQUIRED = False
RESAMPLER_DELAY_HANDLING = (
    "FIR centering and delay handling are performed internally by "
    "scipy.signal.resample_poly; no additional project-level sample shift is applied."
)

__all__ = [
    "BASE_SIGNAL_BANDWIDTH_HZ",
    "ADDITIONAL_DELAY_COMPENSATION_REQUIRED",
    "EDGE_POLICY",
    "EXPLICIT_SAMPLE_SHIFT_APPLIED",
    "FS_INPUT_HZ",
    "INPUT_TIME_ORIGIN_S",
    "MANUAL_GROUP_DELAY_COMPENSATION_APPLIED",
    "NORMALIZED_RATIO_DENOMINATOR",
    "OUTPUT_TIME_ORIGIN_ALIGNED",
    "OUTPUT_TIME_ORIGIN_S",
    "RESAMPLER_CVAL",
    "RESAMPLER_DELAY_HANDLING",
    "RESAMPLER_NAME",
    "RESAMPLER_PADTYPE",
    "RESAMPLER_WINDOW",
    "SAMPLE_RATE_INDEX_MAX",
    "SAMPLE_RATE_INDEX_MIN",
    "SAMPLE_RATE_STEP_HZ",
]
